{% set name = "pytransform3d" %}
{% set version = "1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6cf0e9608019188b82534b55274809b691d6c1d587494d180c31b0cb6e66c11c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - python >=2.7
    - scipy
  run:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - python >=2.7
    - scipy

test:
  imports:
    - pytransform3d

about:
  home: https://github.com/rock-learning/pytransform3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D transformations for Python
  doc_url: https://rock-learning.github.io/pytransform3d/
  dev_url: https://github.com/rock-learning/pytransform3d

extra:
  recipe-maintainers:
    - erikmannerfelt
    - AlexanderFabisch
