{% set name = "pytransform3d" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9560e7b5ccd3282173141c8869b61ba2887ab351c86f2a02c56f8542c6e303f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - python >=2.7
    - scipy
  run:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - python >=2.7
    - scipy

test:
  imports:
    - pytransform3d

about:
  home: https://github.com/rock-learning/pytransform3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D transformations for Python
  doc_url: https://rock-learning.github.io/pytransform3d/
  dev_url: https://github.com/rock-learning/pytransform3d

extra:
  recipe-maintainers:
    - erikmannerfelt
    - AlexanderFabisch
